# MyExperiment Configuration File

# NOTE: genericUser, ambulanceUser or operaUser. Currently, we have no more.
# Make sure the keys under "userPerType" are the same as "appLoopLengthPerType" please.

# Configuration set with appLoopLength = 1 and numberOfApplications = 1300
- numberOfEdge: 100
  placementLogic: "ACO"  # Previously 13
  numberOfApplications: 1300  # New field: total applications to create
  appLoopLength: 1  # Uniform loop length for all applications
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "BEST_FIT"  # Previously 7
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "CLOSEST_FIT"  # Previously 8
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "ILP"  # Previously 14
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "MAX_FIT"  # Previously 9
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "MULTI_OPT"  # Previously 11
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "SIMULATED_ANNEALING"  # Previously 12
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "ACO"  # Previously 13
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "BEST_FIT"  # Previously 7
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "CLOSEST_FIT"  # Previously 8
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "ILP"  # Previously 14
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "MAX_FIT"  # Previously 9
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "MULTI_OPT"  # Previously 11
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "SIMULATED_ANNEALING"  # Previously 12
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "ACO"  # Previously 13
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "BEST_FIT"  # Previously 7
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "CLOSEST_FIT"  # Previously 8
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "ILP"  # Previously 14
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "MAX_FIT"  # Previously 9
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "MULTI_OPT"  # Previously 11
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "SIMULATED_ANNEALING"  # Previously 12
  numberOfApplications: 1300
  appLoopLength: 1
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

# ----------------------------------------------------------------------------------------------------------------
# Configuration set with appLoopLength = 3 and numberOfApplications = 1300
- numberOfEdge: 100
  placementLogic: "ACO"  # Previously 13
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "BEST_FIT"  # Previously 7
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "CLOSEST_FIT"  # Previously 8
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "ILP"  # Previously 14
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "MAX_FIT"  # Previously 9
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "MULTI_OPT"  # Previously 11
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "SIMULATED_ANNEALING"  # Previously 12
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "ACO"  # Previously 13
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "BEST_FIT"  # Previously 7
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "CLOSEST_FIT"  # Previously 8
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "ILP"  # Previously 14
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "MAX_FIT"  # Previously 9
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "MULTI_OPT"  # Previously 11
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "SIMULATED_ANNEALING"  # Previously 12
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "ACO"  # Previously 13
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "BEST_FIT"  # Previously 7
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "CLOSEST_FIT"  # Previously 8
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "ILP"  # Previously 14
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "MAX_FIT"  # Previously 9
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "MULTI_OPT"  # Previously 11
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "SIMULATED_ANNEALING"  # Previously 12
  numberOfApplications: 1300
  appLoopLength: 3
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

# ----------------------------------------------------------------------------------------------------------------
# Configuration set with appLoopLength = 5 and numberOfApplications = 1300
- numberOfEdge: 100
  placementLogic: "ACO"  # Previously 13
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "BEST_FIT"  # Previously 7
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "CLOSEST_FIT"  # Previously 8
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "ILP"  # Previously 14
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "MAX_FIT"  # Previously 9
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "MULTI_OPT"  # Previously 11
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 100
  placementLogic: "SIMULATED_ANNEALING"  # Previously 12
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "ACO"  # Previously 13
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "BEST_FIT"  # Previously 7
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "CLOSEST_FIT"  # Previously 8
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "ILP"  # Previously 14
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "MAX_FIT"  # Previously 9
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "MULTI_OPT"  # Previously 11
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 200
  placementLogic: "SIMULATED_ANNEALING"  # Previously 12
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "ACO"  # Previously 13
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "BEST_FIT"  # Previously 7
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "CLOSEST_FIT"  # Previously 8
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "ILP"  # Previously 14
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "MAX_FIT"  # Previously 9
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "MULTI_OPT"  # Previously 11
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123

- numberOfEdge: 300
  placementLogic: "SIMULATED_ANNEALING"  # Previously 12
  numberOfApplications: 1300
  appLoopLength: 5
  usersPerType:
    genericUser: 176
    ambulanceUser: 20
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123