- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"
  
- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"
  
- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

#  -----------------------

- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

#  -----------------------

- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 100
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

#  -----------------------

- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

#   ------------------------------------------------------
- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

#   ------------------------------------------------------
- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 200
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

#   ------------------------------------------------------

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 1
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

#   ------------------------------------------------------------

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 3
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

#   ------------------------------------------------------------

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

- numberOfEdge: 300
  placementLogic: "ACO"
  numberOfApplications: 1300
  appLoopLength: 5
  placementProcessInterval: 60.0
  usersPerType:
    genericUser: 200  # Interval values in seconds for PR generation per user type
  intervalValues:
    genericUser: 600
  randomSeeds:
    experimentSeed: 33
    locationSeed: 42
    mobilityStrategySeed: 123
    heuristicSeed: 456
  areaName: "dublin"

#   ------------------------------------------------------------